### ISSUE TITLE
Import issue,  style-value-types doesn't get transpiled.

### ISSUE THREAD

**Issue by jan-dh** [Popmotion/popmotion#388]
When doing an import of `tween`and `styler` like so:
```
import { tween, styler } from 'popmotion';
```
 I keep getting errors in IE11. It seems that there's one package (` "../../node_modules/stylefire/node_modules/style-value-types/dist/style-value-types.es.js"`) that doesn't get transpiled with Babel to "normal" javascript.  

<img width="836" alt="screenshot 2018-06-27 15 41 29" src="https://user-images.githubusercontent.com/5801781/41977809-9b31928a-7a20-11e8-8d37-13adcda7f42e.png">

Working with Webpack 4 & Babel 7. Also tried to importing the styler seperatly from and directly from stylefire but that gave the same issue.

**Comment by InventingWithMonster** [comment]
I think I botched a stylefire release. Can you do a clean install of `popmotion@8.30` - this should fix the issue

**Comment by jan-dh** [comment]
Still the same issue I'm afraid. Did a clean install, deleted npm folder.

**Comment by rkhayat** [comment]
We're having similar issues...

Jenkins cannot minify

**Comment by InventingWithMonster** [comment]
@rkhayat is this also with webpack 4? And do you find the remaining Popmotion code is transpired?
