### ISSUE TITLE
react-pose: PoseGroup animations do not work after v3.1.0

### ISSUE THREAD

**Issue by green-arrow** [Popmotion/popmotion#466]
## Describe the bug

When using react-pose v3.1.0 or greater, the enter and exit (and preEnter) poses do not work at all when using PoseGroup.

## How to reproduce

Click the toggle button to change the boxes.

## Expected behaviour

Boxes should animate left to right and right to left.

## Link to CodePen example (or similar)

https://codesandbox.io/s/3y0yqwplz1

## Device information

In which environment are you reproducing the bug?
 - Device: Macbook Pro
 - OS: macOs
 - Browser: Chrome
 - Version 68

## Additional context

If you change the `package.json` file to point to `react-pose` v3.0.0, you will see what I expect the behavior to be, the boxes slide back and forth when clicking the toggle button.

**Comment by klaasman** [comment]
It looks like it's broken when the "unit-type" is different between pose props (e.g. `0` vs `'100%'`). It'll work when you change the `0` to `'0%'`.

**Comment by Andarist** [comment]
@klaasman hm, can't see the difference with your fix - according to my debugging session the problem is that `enter` pose is never resolved (the `x` function is never called), but can't yet pinpoint the underlaying problem

**Comment by Andarist** [comment]
Ok, I've found the source of my problems and I suspect the original problem is similar.

This is the [first faulty call](https://github.com/Popmotion/popmotion/blob/415e2563d25078feb04ea3300269603ebe543c63/packages/pose-core/src/factories/setter.ts#L183) to [this](https://github.com/Popmotion/popmotion/blob/415e2563d25078feb04ea3300269603ebe543c63/packages/popmotion-pose/src/dom/pose.ts#L87). `x` being a function got normalized to 0 by accident. But because the function resolving happens [later](https://github.com/Popmotion/popmotion/blob/415e2563d25078feb04ea3300269603ebe543c63/packages/pose-core/src/factories/setter.ts#L221) I suspect this whole process needs to be slightly refactored, because ideally we should to the normalization in 1 place - therefore we need to resolve functions upfront and normalize returned values, cant do the other way around (like now)

**Comment by green-arrow** [comment]
@Andarist @klaasman - If you update the CodeSandbox I posted to use `'0%'` in the `enter` transition, you'll see that `enter` and `preEnter` work, but it appears that the `exit` transition is never called.

**Comment by Andarist** [comment]
That's because the exit's `x` is normalized wrongfully to 0 without the function being resolved.

**Comment by Andarist** [comment]
It's fixed in latest version 🎉 so the issue can be closed

**Comment by green-arrow** [comment]
@Andarist - I just updated the codepen above to 3.3.2, but it still doesn't work correctly. The first animation plays out fine, but when toggling a second time, the exit animation doesn't play. Additionally, after the second time, the animation never plays again at all.

**Comment by green-arrow** [comment]
@Andarist - Update - when using 3.3.1, the animation works correctly. Seems to be a regression with 3.3.2.

**Comment by InventingWithMonster** [comment]
@green-arrow I've got a good idea of what's causing this, fix will be 10 min

**Comment by InventingWithMonster** [comment]
@green-arrow Please try 3.3.3

**Comment by green-arrow** [comment]
@InventingWithMonster - 3.3.3 works correctly, thanks!
