### ISSUE TITLE
Children button "onClick" not triggering when parent div "draggable" = true

### ISSUE THREAD

**Issue by yuensunn** [Popmotion/popmotion#541]
Tried reading the documentation but could not find any solution. Am I missing something?
Currrently using:-
- "react" : "^16.5.2"
- "react-pose": "^3.3.6",

**Comment by yuensunn** [comment]
I just realized that it is working fine on pc but it wont work on mobile.

**Comment by JavierFVasquez** [comment]
Hey, someone has already fixed this bug? I have waiting one month but apearly this bug doesn't matter to anyone

**Comment by Andarist** [comment]
Hm, im unfortunately not sure how to fix it either :s Could u maybe track `touchstart` instead of click and emulate the event yourself? 

This is tricky because we have to call preventDefault but at the moment touchstart happens we cant know if its intended as dragstart or just a click

**Comment by dbismut** [comment]
Hi @andarist, thanks for your answer. I agree, no way to know if it’s a drag or a click on touch start but popmotion preventsDefault on the start and end events for draggable elements no matter what. So in a way it’s already too late to do any check after the element has been instantiated I believe... otherwise yes, we could calculate the drag distance on drag end and prevent default if the distance is different than zero.

**Comment by Andarist** [comment]
We cant determine if we should call preventDefault on touchstart though. Would omitting preventDefault just on touched allow onClick to be called?

**Comment by dbismut** [comment]
Ok so further clarification after some tests: to register a click on iOS, you need to remove `preventDefault` on `touchstart` **and** `touchend`. However, if you do this, document will then register scroll events and therefore when you drag the draggable element you will also scroll the viewport. 

I thought popmotion `multitouch/index.ts` was preventing default on `touchmove` events, but it doesn't seem to have any effect and the viewport keeps scrolling on drag.

I'm not exactly sure why this works, but if you set `preventDefault` to false in the draggable configuration of `popmotion-pose` in `events.ts` and then implement the draggable element as follows:

```js
class Example extends Component {
  onClick = e => {
    console.log('onClick', e);
  };

  componentDidMount() {
    this.el.addEventListener('touchmove', () => {});
   // this should do nothing but it actually prevents the scroll for some reason
  }

  render() {
    return (
      <Box ref={el => (this.el = el)} className="box" onClick={this.onClick}>
        <button onClick={() => alert('click')}>Click me</button>
      </Box>
    );
  }
}
```

... then the draggable registers clicks and doesn't scroll the viewport (on my iPhone at least).

**Comment by Andarist** [comment]
Web programming at its finest 😂Great investigation! Im not sure what w should do about it though - I guess we at least should make `preventDefault` configurable, right?

**Comment by dbismut** [comment]
That would be a temp fix but it would be a start I guess, but yeah I know, that's just silly! Actually I think the listener works because it implicitly passes `passive: false` as a third argument to `addEventListener`.

Also note that having a functional overflowing-x div _within_ the draggable requires another tweak 🙈:

```js
class Example extends Component {
  startPosition = null;
  lockHasBeenCalculated = false;
  preventDrag = false;

  componentDidMount() {
    this.el.addEventListener('touchmove', () => {}, { passive: false });
    this.scroll.addEventListener('touchstart', e => {
      this.preventDrag = false;
      this.lockHasBeenCalculated = false;

      if (e.touches.length > 1) this.lockHasBeenCalculated = true;
      
      else {
        const { pageX, pageY } = e.touches[0];
        this.startPosition = { x: pageX, y: pageY };
      }

    });

    this.scroll.addEventListener('touchmove', e => {
      if (!this.lockHasBeenCalculated) {
        const { pageX, pageY } = e.touches[0];
        const distanceX = Math.abs(this.startPosition.x - pageX);
        const distanceY = Math.abs(this.startPosition.y - pageY);
        if (distanceX > distanceY) {
          this.preventDrag = true;
          this.lockHasBeenCalculated = true;
        } else if (distanceX < distanceY) {
          this.lockHasBeenCalculated = true;
        }
      }
      if (this.preventDrag) {
        e.stopPropagation();
      }
    });
  }

  render() {
    return (
      <Box ref={el => (this.el = el)} className="box">
        <button onClick={() => alert('click')}>Click me</button>
        <div className="overflow" ref={scroll => (this.scroll = scroll)}>
          <div />
          <div />
          <div />
          <div />
          <div />
          <div />
          <div />
          <div />
          <div />
        </div>
      </Box>
    );
  }
}
```

**Comment by dbismut** [comment]
Hey @andarist, I’ve just issued a pull request that should fix the click problem on mobile. It involves adding a touch move listener to the draggable element and preventing default from there instead of in touch start of end.

**Comment by alxsavard** [comment]
Hi there! 

I'm still having this exact problem. I didn't follow the whole thread, but try clicking this button on an _ANDROID_ mobile device: https://codesandbox.io/s/3ypx3zzpxp

I'm running the latest react-pose (4.0.4 as per npm).

Am I missing something? 

(it does seems to work on iphone though)

**Comment by publicJorn** [comment]
Also still have the problem. A draggable `posed.div` with a link as child; the link is not clickable on a touch device (ipad, smartphone, even in chrome dev tools with device toolbar.

I know this is an old thread, but hope to find some answers!

**Comment by matiasj899** [comment]
i have the same problem but happens when the view is 1440p

**Comment by daxdesai** [comment]
Use the **cancel** prop on the <Draggable> component to exclude the delete button (and anything else you want to make clickable) from being draggable.

You can do this using a CSS selector. Here's how:

✅ Fix Implementation

Add a class to the delete button (e.g., not-draggable).

Use the cancel prop in Draggable to ignore dragging on that class.

```
<Draggable
  key={data._id}
  axis="both"
  allowAnyClick
  defaultPosition={{ x: 10, y: 10 }}
  onStop={(e, d) => handleDragStop(e, d, index)}
  cancel=".not-draggable" // 👈 Add this
>
```

Then, update the delete button like this:

```
<button
  type="button"
  title="Delete"
  className="not-draggable"
  onClick={(e) => {
    e.stopPropagation();
    handleDelete(data._id);
  }}
>
  Delete
</button>
```

💡 Why It Works

The cancel prop tells react-draggable to ignore drag events on elements that match the selector, letting normal click events happen instead.
