### ISSUE TITLE
applyAtEnd doesnt get applied on mount unless it actually changes pose?

### ISSUE THREAD

**Issue by k90armstrong** [Popmotion/popmotion#589]
## Describe the bug
Maybe this is how the `applyAtEnd` is intended to work, but I am looking for a solution to the following.  I want to create a Fade component that will apply `display: none` at the end of the animation.  I also want it to have `display: none` when it is mounted and should not be shown (no change in pose will have been initialized).

## How to reproduce
see the code sandbox example, i would like for the second h2 to have `display: none` 
https://codesandbox.io/s/3vyz87ry8m

I tried to look through the docs but was unable to locate an answer.  Thanks for your help and patience if i just missed it somewhere!

**Comment by Andarist** [comment]
It seems that this got fixed by https://github.com/Popmotion/popmotion/commit/291ed53cf51ed2529eb25012026d19e5cc9a6f95 but the 2.0.1 version has never been published, cc @InventingWithMonster

**Comment by k90armstrong** [comment]
Hey guys, any idea on what to do about this issue? If the fix here 291ed53 can be merged and published that would be awesome! Thanks!

**Comment by Andarist** [comment]
@InventingWithMonster pose-core needs a release, the code currently on master is not published

**Comment by Andarist** [comment]
@InventingWithMonster friendly 🏓 as yo uare doing releases right now, pose-core needs a fresh release too :)

**Comment by InventingWithMonster** [comment]
👍

**Comment by Andarist** [comment]
@k90armstrong could u confirm that ur issue has been resolved and close the ticket? :)

**Comment by k90armstrong** [comment]
@Andarist, I updated the dependency here => https://codesandbox.io/s/vq87xvm507 and it looks like it is still not applying the `display: none` as expected. The new version is 4.0.3 correct?

**Comment by Andarist** [comment]
You have to force a new version of pose-core (which is dep of react-pose). I've added it here - https://codesandbox.io/s/ll0nq24l9 and indeed it doesn't seem to work, I'll dive into fixing it this week (hopefully).

**Comment by Andarist** [comment]
Ok, so this works if you do a fresh install. I have no idea why it is not working on codesandbox, it has cached things too much.

I've literally downloaded the sandbox on my machine, unpackd the archive, done `npm install && npm start` and confirmed that it works.
